development:
  adapter: jdbcpostgresql
  database: bidding-development
  username: james
  password: 'password'
  pool: 30

test: &test
  adapter: jdbcpostgresql
  database: bidding-test<%= ENV['TEST_ENV_NUMBER'] %>
  username: james
  password: 'password'
  pool: 30

production:
  adapter: jdbcpostgresql
  database: bidding-production
  username: james
  password: 'password'
  pool: 30
