development:
  adapter: postgresql
  database: bidding-development
  username: james
  password: 'password'
  pool: 60
  reaping_frequency: 2

test: &test
  adapter: postgresql
  database: bidding-test<%= ENV['TEST_ENV_NUMBER'] %>
  username: james
  password: 'password'
  pool: 30

production:
  adapter: postgresql
  database: bidding-production
  username: james
  password: 'password'
  pool: 30
